name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


jobs:
  fedora:
    name: Linux Fedora (Debug, GCC, cxx11)
    runs-on: ubuntu-latest
    container: dynawo/dynawo-ci:latest
    strategy:
      fail-fast: false
    env:
      DYNAFLOW_LAUNCHER_BUILD_TYPE: Debug
      DYNAFLOW_LAUNCHER_PROCESSORS_USED: 2
      DYNAFLOW_LAUNCHER_FORCE_CXX11_ABI: "true"
      DYNAFLOW_LAUNCHER_LOCALE: "en_GB"
      COMPILER_FOLDER: "gcc5.3.1"
      ZIP_ALGORITHMS: "dynawo-algorithms-cxx11-nightly.zip"
      ZIP_DYNAWO: "dynawo-cxx11-nightly.zip"

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Fetch Dynawo
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          repo: "dynawo/dynawo"
          version: "tags/nightly"
          file: "${{ env.ZIP_DYNAWO }}"
          target: "dynawo/dynawo.zip"
          token: "${{ secrets.GITHUB_TOKEN }}"

      - name: Extract Dynawo
        run: |
          cd dynawo
          unzip -qq "dynawo.zip"
          cd ..

      - name: Fetch Dynawo algorithms
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          repo: "dynawo/dynawo-algorithms"
          version: "tags/nightly"
          file: "${{ env.ZIP_ALGORITHMS }}"
          target: "dynawo-algorithms/dynawo-algorithms.zip"
          token: "${{ secrets.GITHUB_TOKEN }}"

      - name: Extract Dynawo algorithms
        run: |
          cd dynawo-algorithms
          unzip -qq "dynawo-algorithms.zip"
          cd ..

      - name: Load persistent build files
        uses: actions/cache@v2
        with:
          # A list of files, directories, and wildcard patterns to cache and restore
          path: |
            build
            install
          # An explicit key for restoring and saving the cache
          key: ${{ runner.os }}-cmake

      - name: Build
        run: |
          export DYNAWO_HOME=$(pwd)/dynawo
          export DYNAWO_ALGORITHMS_HOME=$(pwd)/dynawo_algorithms
          export DYNAFLOW_LAUNCHER_HOME=$(pwd)
          scripts/envDFL.sh build-user

      - name: Run tests
        run: |
          export DYNAWO_HOME=$(pwd)/dynawo
          export DYNAWO_ALGORITHMS_HOME=$(pwd)/dynawo_algorithms
          export DYNAFLOW_LAUNCHER_HOME=$(pwd)
          scripts/envDFL.sh tests
